/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "IBM Plex Sans",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "sans-serif",
        ],
      },
      spacing: {
        "carbon-01": "var(--spacing-01)",
        "carbon-02": "var(--spacing-02)",
        "carbon-03": "var(--spacing-03)",
        "carbon-04": "var(--spacing-04)",
        "carbon-05": "var(--spacing-05)",
        "carbon-06": "var(--spacing-06)",
        "carbon-07": "var(--spacing-07)",
        "carbon-08": "var(--spacing-08)",
        "carbon-09": "var(--spacing-09)",
        "carbon-10": "var(--spacing-10)",
      },
      colors: {
        "dark-blue": "#1E4D91",
        "campus-green": "#2BA56A",
        "light-blue": "#3498DB",
        "dark-gray": "#333333",
        "medium-gray": "#666666",
        "light-gray": "#E5E5E5",
        "soft-blue": "#4A90E2",
        "green-status": "#27AE60",
        "campus-blue-light": "#2C6FB0",
        "campus-blue-dark": "#1F4F87",
        "circle-teal-light": "#4DB9A6",
        "circle-teal-dark": "#2C8C77",
        carbon: {
          gray: {
            10: "var(--gray-10)",
            20: "var(--gray-20)",
            30: "var(--gray-30)",
            40: "var(--gray-40)",
            50: "var(--gray-50)",
            60: "var(--gray-60)",
            70: "var(--gray-70)",
            80: "var(--gray-80)",
            90: "var(--gray-90)",
            100: "var(--gray-100)",
          },
          blue: {
            10: "var(--blue-10)",
            20: "var(--blue-20)",
            30: "var(--blue-30)",
            40: "var(--blue-40)",
            50: "var(--blue-50)",
            60: "var(--blue-60)",
            70: "var(--blue-70)",
            80: "var(--blue-80)",
            90: "var(--blue-90)",
            100: "var(--blue-100)",
          },
          red: {
            10: "var(--red-10)",
            20: "var(--red-20)",
            30: "var(--red-30)",
            40: "var(--red-40)",
            50: "var(--red-50)",
            60: "var(--red-60)",
            70: "var(--red-70)",
            80: "var(--red-80)",
          },
          green: {
            10: "var(--green-10)",
            20: "var(--green-20)",
            30: "var(--green-30)",
            40: "var(--green-40)",
            50: "var(--green-50)",
            60: "var(--green-60)",
            70: "var(--green-70)",
          },
          yellow: {
            20: "var(--yellow-20)",
            30: "var(--yellow-30)",
            40: "var(--yellow-40)",
          },
        },
        primary: {
          50: "#f0f4fd",
          100: "#e1e9fb",
          200: "#c3d3f7",
          300: "#9bb5f1",
          400: "#6b8ee8",
          500: "#4A90E2",
          600: "#3498DB",
          700: "#1E4D91",
          800: "#1a4080",
          900: "#163366",
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          50: "#f9f9f9",
          100: "#f5f5f5",
          200: "#E5E5E5",
          300: "#d4d4d4",
          400: "#a3a3a3",
          500: "#666666",
          600: "#525252",
          700: "#404040",
          800: "#333333",
          900: "#262626",
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        success: {
          50: "#f0fdf4",
          100: "#dcfce7",
          200: "#bbf7d0",
          300: "#86efac",
          400: "#4ade80",
          500: "#27AE60",
          600: "#2BA56A",
          700: "#15803d",
          800: "#166534",
          900: "#14532d",
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
